version: "2"

services:
  golang-testing:
    build:
      context: ./golang
      args:
        PROJECT_PATH: $PROJECT_PATH
    privileged: true
    environment:
      - PROJECT_PATH
    volumes:
      - ../:$PROJECT_PATH
    command: sh -c "make update && coverage all"
